"""add_last_parsed_id_to_communities

Revision ID: 2529deb992d7
Revises: a6bf41d07cb6
Create Date: 2026-01-20 21:03:19.820503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2529deb992d7'
down_revision: Union[str, None] = 'a6bf41d07cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('last_parsed_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'last_parsed_id')
    # ### end Alembic commands ###
