"""add_clicks_reactions_summary

Revision ID: 7c1b5f0c2a1f
Revises: 2529deb992d7
Create Date: 2026-01-21 00:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1b5f0c2a1f'
down_revision: Union[str, None] = '2529deb992d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('summary_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.create_table(
        'clicks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_clicks_id'), 'clicks', ['id'], unique=False)
    op.create_index(op.f('ix_clicks_post_id'), 'clicks', ['post_id'], unique=False)
    op.create_index(op.f('ix_clicks_user_id'), 'clicks', ['user_id'], unique=False)
    op.create_unique_constraint('uq_reactions_user_post', 'reactions', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reactions_user_post', 'reactions', type_='unique')
    op.drop_index(op.f('ix_clicks_user_id'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_post_id'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_id'), table_name='clicks')
    op.drop_table('clicks')
    op.drop_column('users', 'summary_enabled')
    # ### end Alembic commands ###
