"""add_metrics_keywords_engagement

Revision ID: 9d5f8e2c0f1a
Revises: 7c1b5f0c2a1f
Create Date: 2026-01-21 00:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5f8e2c0f1a'
down_revision: Union[str, None] = '7c1b5f0c2a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('engagement_score', sa.Float(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('reactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True))
    op.add_column('reactions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True))
    op.add_column('clicks', sa.Column('community_id', sa.Integer(), nullable=True))
    op.add_column('clicks', sa.Column('click_count', sa.Integer(), server_default='1', nullable=False))
    op.add_column('clicks', sa.Column('first_clicked_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True))
    op.add_column('clicks', sa.Column('last_clicked_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True))
    op.create_index(op.f('ix_clicks_community_id'), 'clicks', ['community_id'], unique=False)
    op.create_unique_constraint('uq_clicks_user_post', 'clicks', ['user_id', 'post_id'])
    op.create_table(
        'user_keyword_stats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('keyword', sa.String(), nullable=True),
        sa.Column('clicks_count', sa.Integer(), server_default='0', nullable=False),
        sa.Column('reactions_count', sa.Integer(), server_default='0', nullable=False),
        sa.Column('score', sa.Float(), server_default='0', nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'keyword', name='uq_user_keyword'),
    )
    op.create_index(op.f('ix_user_keyword_stats_id'), 'user_keyword_stats', ['id'], unique=False)
    op.create_index(op.f('ix_user_keyword_stats_keyword'), 'user_keyword_stats', ['keyword'], unique=False)
    op.create_index(op.f('ix_user_keyword_stats_user_id'), 'user_keyword_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_keyword_stats_user_id'), table_name='user_keyword_stats')
    op.drop_index(op.f('ix_user_keyword_stats_keyword'), table_name='user_keyword_stats')
    op.drop_index(op.f('ix_user_keyword_stats_id'), table_name='user_keyword_stats')
    op.drop_table('user_keyword_stats')
    op.drop_constraint('uq_clicks_user_post', 'clicks', type_='unique')
    op.drop_index(op.f('ix_clicks_community_id'), table_name='clicks')
    op.drop_column('clicks', 'last_clicked_at')
    op.drop_column('clicks', 'first_clicked_at')
    op.drop_column('clicks', 'click_count')
    op.drop_column('clicks', 'community_id')
    op.drop_column('reactions', 'updated_at')
    op.drop_column('reactions', 'created_at')
    op.drop_column('posts', 'keywords')
    op.drop_column('users', 'engagement_score')
    # ### end Alembic commands ###
